version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.1
workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: main
          mapping: |
            apps/client/.* client-modified true
            apps/chat-ui/.* chat-modified true
            apps/events-ui/.* events-modified true
          config-path: .circleci/workflows.yml
