version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

parameters:
  client-modified:
    type: boolean
    default: false
  chat-modified:
    type: boolean
    default: false
  events-modified:
    type: boolean
    default: false

jobs:
  build-client:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build client
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: dist/apps/client
          to: 's3://pokedexe-ui'
  build-chat:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build chat-ui
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: dist/apps/chat-ui
          to: 's3://pokedexe-ui/chat'
  build-events:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build events-ui
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: dist/apps/events-ui
          to: 's3://pokedexe-ui/events'
workflows:
  deploy-client:
    when: << pipeline.parameters.client-modified >>
    jobs:
      - build-client
  deploy-events:
    when: << pipeline.parameters.events-modified >>
    jobs:
      - build-events
  deploy-chat:
    when: << pipeline.parameters.chat-modified >>
    jobs:
      - build-chat
