version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.0
commands:
  upload-batch:
    parameters:
      from:
        type: string
      to:
        type: string
    steps:
      - run: az storage blob delete-batch --source << parameters.to >>
      - run: az storage blob upload-batch --destination << parameters.to >> --source << parameters.from >>
parameters:
  client-modified:
    type: boolean
    default: false
  chat-modified:
    type: boolean
    default: false
  events-modified:
    type: boolean
    default: false

jobs:
  build-client:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build client
      - persist_to_workspace:
          root: .
          paths:
            - dist/apps/client
  build-chat:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build chat-ui
      - persist_to_workspace:
          root: .
          paths:
            - dist/apps/chat-ui
  build-events:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build events-ui
      - persist_to_workspace:
          root: .
          paths:
            - dist/apps/events-ui
  upload-chat:
    executor: azure-cli/default
    steps:
      - attach_workspace:
          at: .
      - azure-cli/install
      - upload-batch:
          from: dist/apps/chat-ui
          to: chat
  upload-events:
    executor: azure-cli/default
    steps:
      - attach_workspace:
          at: .
      - azure-cli/install
      - upload-batch:
          from: dist/apps/events-ui
          to: events
  upload-client:
    executor: azure-cli/default
    steps:
      - attach_workspace:
          at: .
      - azure-cli/install
      - upload-batch:
          from: dist/apps/client
          to: \$web
workflows:
  deploy-client:
    when: << pipeline.parameters.client-modified >>
    jobs:
      - build-client:
          filters:
            branches:
              only:
                - main
      - upload-client:
          requires:
            - build-client
  deploy-events:
    when: << pipeline.parameters.events-modified >>
    jobs:
      - build-events:
          filters:
            branches:
              only:
                - main
      - upload-events:
          requires:
            - build-events
  deploy-chat:
    when: << pipeline.parameters.chat-modified >>
    jobs:
      - build-chat:
          filters:
            branches:
              only:
                - main
      - upload-chat:
          requires:
            - build-chat
