name: Deploy Web Api

on:
  push:
    branches:
      - main
    paths:
      - 'apps/query-api/**'
      - 'libs/persistence/**'
      - 'libs/domain/**'
      - 'libs/application/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: boochat.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build -f docker/command-api.dockerfile . -t boochat.azurecr.io/command-api:latest
          docker push boochat.azurecr.io/command-api:latest
